### ISSUE TITLE
coupon vs. new_coupon

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/oo-through-associations#3]
Perhaps having this mistake with an undefined variable is actually a good thing, because at this point in the curriculum it should be an easy correction and the student can feel empowered my her/his attention to detail.  Nevertheless, you might want to just fix it.

In Step 2: Building the Belongs to Association, when you redefine the #buy_cd method it looks like this:
 def buy_cd(cd)
    self.cd_collection << cd
    cd.teen = self
    new_coupon = Coupon.new
    cd.coupon = new_coupon
    coupon.cd = cd
  end

Notice in the last line that "coupon" is an undefined variable. It should be "new_coupon", as it is set 2 lines before.

**Comment by SophieDeBenedetto** [comment]
fixed.
